spec:
  containers:
    - name: mlops-app
      image: faheemkhan08/gitops-project:latest
      ports:
        - containerPort: 5000
      readinessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 5000
        initialDelaySeconds: 15
        periodSeconds: 10
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"